package be.e1.bssv.J564200.DeleteShipmentProxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Tue May 20 15:01:04 EDT 2014  
 */

public interface DeleteFedExShipment extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/FedExShipServices/FedExShipments/deleteFedExShipment}delete   */

  public be.e1.bssv.J564200.com.beone.fedex.beshipments.ShipmentReply delete(be.e1.bssv.J564200.com.beone.fedex.beshipments.DeleteShipmentRequest payload) throws java.rmi.RemoteException;
    public void deleteAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.J564200.com.beone.fedex.beshipments.DeleteShipmentRequest payload) throws java.rmi.RemoteException ;
  
}