package be.e1.bssv.J564200.DeleteShipmentProxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Tue May 20 15:01:04 EDT 2014  
 */

public interface Deletefedexshipment_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: DeleteFedExShipment_Pt  
     // Port Type: DeleteFedExShipment   
     //***********************************
     
  /**
   * returns DeleteFedExShipment_Pt port in this service 
   */
  be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getDeleteFedExShipment_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment getDeleteFedExShipment_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }