package be.e1.bssv.J564200.DeleteShipmentProxy;

/**
 * Generated class, do not edit.
 *
 * This stub class was generated by weblogic
 * webservice stub gen on Tue May 20 15:01:04 EDT 2014 
 */

public class DeleteFedExShipment_Stub 
     extends weblogic.wsee.jaxrpc.StubImpl
     implements be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment, /**/java.io.Serializable
{

  public DeleteFedExShipment_Stub(weblogic.wsee.wsdl.WsdlPort port, 
                        weblogic.wsee.jaxrpc.ServiceImpl service) 
    throws javax.xml.rpc.ServiceException
  {
    super(port, be.e1.bssv.J564200.DeleteShipmentProxy.DeleteFedExShipment.class, service);
  }
  
    
  /**
   * Operation Name : {http://xmlns.oracle.com/FedExShipServices/FedExShipments/deleteFedExShipment}delete   */

  public be.e1.bssv.J564200.com.beone.fedex.beshipments.ShipmentReply delete(be.e1.bssv.J564200.com.beone.fedex.beshipments.DeleteShipmentRequest payload) throws java.rmi.RemoteException {

    java.util.ArrayList _args = new java.util.ArrayList();
    _args.add(payload);
    
    try {
            java.lang.Object _result = _invoke("delete", _args.toArray());
      return (be.e1.bssv.J564200.com.beone.fedex.beshipments.ShipmentReply)_result;
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {

      
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
  }  public void deleteAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.J564200.com.beone.fedex.beshipments.DeleteShipmentRequest payload) throws java.rmi.RemoteException  {
    java.util.ArrayList _args = new java.util.ArrayList();

    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY, "true");
    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY, apc);
    _setProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY, "delete");
    _setProperty(weblogic.wsee.async.AsyncConstants.OPERATION_NAME_PROPERTY,
                 "delete");
    _setProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY, "be.e1.bssv.J564200.com.beone.fedex.beshipments.ShipmentReply");
    _args.add(payload);
    
    try {
      java.lang.Object _result = _invoke("delete", _args.toArray());
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
    finally {
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY);

    }
  }
   
    
  private Object writeReplace() throws java.io.ObjectStreamException {
    java.util.HashMap map = new java.util.HashMap();
            map.put("deleteFedExShipment_pt", "DeleteFedExShipment_Pt");
            
    return new weblogic.wsee.tools.clientgen.stubgen.StubSerialWrapper(
      "be.e1.bssv.J564200.DeleteShipmentProxy.Deletefedexshipment_Client_Ep",
      (String)map.get(_getPortName()),
      _getUserProperties());
  }
}