package be.e1.bssv.J563000.ItemBOMNotifyProxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Jan 16 15:40:22 EST 2014  
 */

public interface Processitembomnotification_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ProcessItemBOMNotification_Pt  
     // Port Type: ProcessItemBOMNotification   
     //***********************************
     
  /**
   * returns ProcessItemBOMNotification_Pt port in this service 
   */
  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getProcessItemBOMNotification_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }