package be.e1.bssv.J563000.ItemBOMNotifyProxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Jan 16 15:40:22 EST 2014  
 */

public interface ProcessItemBOMNotification extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/P2SINT0001/ItemBOMNotification/processItemBOMNotification}process   */

  public be.e1.bssv.J563000.com.beav.plm.itembomnotification.ItemBOMNotificationResponse process(be.e1.bssv.J563000.com.beav.plm.itembomnotification.ItemBOMNotification payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.J563000.com.beav.plm.itembomnotification.ItemBOMNotification payload) throws java.rmi.RemoteException ;
  
}