package be.e1.bssv.J563000.ItemBOMNotifyProxy;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Thu Jan 16 15:40:22 EST 2014 */

public class Processitembomnotification_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.J563000.ItemBOMNotifyProxy.Processitembomnotification_Client_Ep {

  public Processitembomnotification_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/J563000/ItemBOMNotifyProxy/Processitembomnotification_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public Processitembomnotification_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public Processitembomnotification_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://xmlns.oracle.com/P2SINT0001/ItemBOMNotification/processItemBOMNotification", "processitembomnotification_client_ep"),
          "be/e1/bssv/J563000/ItemBOMNotifyProxy/Processitembomnotification_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: ProcessItemBOMNotification_Pt 
  // Port Type: ProcessItemBOMNotification 
  //***********************************

  be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification mvar_ProcessItemBOMNotification_Pt;

  /**
   * returns ProcessItemBOMNotification_Pt port in this service 
   */
  public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_ProcessItemBOMNotification_Pt == null) {
      mvar_ProcessItemBOMNotification_Pt =
        new be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification_Stub(_getPort("processItemBOMNotification_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_ProcessItemBOMNotification_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_ProcessItemBOMNotification_Pt;
  }

  /**
   * @Deprecated  Use getProcessItemBOMNotification_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getProcessItemBOMNotification_Pt();
  }

  public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getProcessItemBOMNotification_Pt();
  }
  
      public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processItemBOMNotification_pt", policyInputStream, true, true);
    return getProcessItemBOMNotification_Pt();
  }

  public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processItemBOMNotification_pt", policyInputStream, inbound, outbound);
    return getProcessItemBOMNotification_Pt();
  }
 
  public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processItemBOMNotification_pt", null, inboundPolicies, outboundPolicies);
    return getProcessItemBOMNotification_Pt();
  }
  
  public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processItemBOMNotification_pt", null, inboundPolicies, outboundPolicies);
    return getProcessItemBOMNotification_Pt();
  }
  
  public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processItemBOMNotification_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessItemBOMNotification_Pt();
  }
  
  public be.e1.bssv.J563000.ItemBOMNotifyProxy.ProcessItemBOMNotification getProcessItemBOMNotification_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processItemBOMNotification_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessItemBOMNotification_Pt();
  }
    
}