package be.e1.bssv.util.J5606001.timetracproxy;

/**
 * Generated class, do not edit.
 *
 * This stub class was generated by weblogic
 * webservice stub gen on Mon Feb 10 14:26:08 EST 2014 
 */

public class H2RINT0010BPEL_Stub 
     extends weblogic.wsee.jaxrpc.StubImpl
     implements be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL, /**/java.io.Serializable
{

  public H2RINT0010BPEL_Stub(weblogic.wsee.wsdl.WsdlPort port, 
                        weblogic.wsee.jaxrpc.ServiceImpl service) 
    throws javax.xml.rpc.ServiceException
  {
    super(port, be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL.class, service);
  }
  
    
  /**
   * Operation Name : {http://www.beaerospace.com/H2RINT0010/H2RINT0010/H2RINT0010BPEL}process   */

  public void process(java.lang.String input) throws java.rmi.RemoteException {

    java.util.ArrayList _args = new java.util.ArrayList();
    _args.add(input);
    
    try {
            java.lang.Object _result = _invoke("process", _args.toArray());
          } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {

      
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
  } 
    
  private Object writeReplace() throws java.io.ObjectStreamException {
    java.util.HashMap map = new java.util.HashMap();
            map.put("H2RINT0010BPEL_pt", "H2RINT0010BPEL_Pt");
            
    return new weblogic.wsee.tools.clientgen.stubgen.StubSerialWrapper(
      "be.e1.bssv.util.J5606001.timetracproxy.H2Rint0010Bpel_Client_Ep",
      (String)map.get(_getPortName()),
      _getUserProperties());
  }
}