package be.e1.bssv.util.J5606001.timetracproxy;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Mon Feb 10 14:26:08 EST 2014 */

public class H2Rint0010Bpel_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.util.J5606001.timetracproxy.H2Rint0010Bpel_Client_Ep {

  public H2Rint0010Bpel_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/util/J5606001/timetracproxy/H2Rint0010Bpel_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public H2Rint0010Bpel_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public H2Rint0010Bpel_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://www.beaerospace.com/H2RINT0010/H2RINT0010/H2RINT0010BPEL", "h2rint0010bpel_client_ep"),
          "be/e1/bssv/util/J5606001/timetracproxy/H2Rint0010Bpel_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: H2RINT0010BPEL_Pt 
  // Port Type: H2RINT0010BPEL 
  //***********************************

  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL mvar_H2RINT0010BPEL_Pt;

  /**
   * returns H2RINT0010BPEL_Pt port in this service 
   */
  public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_H2RINT0010BPEL_Pt == null) {
      mvar_H2RINT0010BPEL_Pt =
        new be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL_Stub(_getPort("H2RINT0010BPEL_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_H2RINT0010BPEL_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_H2RINT0010BPEL_Pt;
  }

  /**
   * @Deprecated  Use getH2RINT0010BPEL_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getH2RINT0010BPEL_Pt();
  }

  public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getH2RINT0010BPEL_Pt();
  }
  
      public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("H2RINT0010BPEL_pt", policyInputStream, true, true);
    return getH2RINT0010BPEL_Pt();
  }

  public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("H2RINT0010BPEL_pt", policyInputStream, inbound, outbound);
    return getH2RINT0010BPEL_Pt();
  }
 
  public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("H2RINT0010BPEL_pt", null, inboundPolicies, outboundPolicies);
    return getH2RINT0010BPEL_Pt();
  }
  
  public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("H2RINT0010BPEL_pt", null, inboundPolicies, outboundPolicies);
    return getH2RINT0010BPEL_Pt();
  }
  
  public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("H2RINT0010BPEL_pt", operationName, inboundPolicies, outboundPolicies);
    return getH2RINT0010BPEL_Pt();
  }
  
  public be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("H2RINT0010BPEL_pt", operationName, inboundPolicies, outboundPolicies);
    return getH2RINT0010BPEL_Pt();
  }
    
}