package be.e1.bssv.util.J5606001.timetracproxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Mon Feb 10 14:26:08 EST 2014  
 */

public interface H2RINT0010BPEL extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://www.beaerospace.com/H2RINT0010/H2RINT0010/H2RINT0010BPEL}process   */

  public void process(java.lang.String input) throws java.rmi.RemoteException;
  
}