package be.e1.bssv.util.J5606001.timetracproxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Mon Feb 10 14:26:08 EST 2014  
 */

public interface H2Rint0010Bpel_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: H2RINT0010BPEL_Pt  
     // Port Type: H2RINT0010BPEL   
     //***********************************
     
  /**
   * returns H2RINT0010BPEL_Pt port in this service 
   */
  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getH2RINT0010BPEL_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J5606001.timetracproxy.H2RINT0010BPEL getH2RINT0010BPEL_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }