package be.e1.bssv.J563004.ecoproxy;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Fri Jan 17 16:26:00 EST 2014 */

public class Processecnnotification_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.J563004.ecoproxy.Processecnnotification_Client_Ep {

  public Processecnnotification_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/J563004/ecoproxy/Processecnnotification_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public Processecnnotification_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public Processecnnotification_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://xmlns.oracle.com/P2SINT0001/ECNNotification/processECNNotification", "processecnnotification_client_ep"),
          "be/e1/bssv/J563004/ecoproxy/Processecnnotification_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: ProcessECNNotification_Pt 
  // Port Type: ProcessECNNotification 
  //***********************************

  be.e1.bssv.J563004.ecoproxy.ProcessECNNotification mvar_ProcessECNNotification_Pt;

  /**
   * returns ProcessECNNotification_Pt port in this service 
   */
  public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_ProcessECNNotification_Pt == null) {
      mvar_ProcessECNNotification_Pt =
        new be.e1.bssv.J563004.ecoproxy.ProcessECNNotification_Stub(_getPort("processECNNotification_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_ProcessECNNotification_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_ProcessECNNotification_Pt;
  }

  /**
   * @Deprecated  Use getProcessECNNotification_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getProcessECNNotification_Pt();
  }

  public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getProcessECNNotification_Pt();
  }
  
      public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processECNNotification_pt", policyInputStream, true, true);
    return getProcessECNNotification_Pt();
  }

  public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processECNNotification_pt", policyInputStream, inbound, outbound);
    return getProcessECNNotification_Pt();
  }
 
  public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processECNNotification_pt", null, inboundPolicies, outboundPolicies);
    return getProcessECNNotification_Pt();
  }
  
  public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processECNNotification_pt", null, inboundPolicies, outboundPolicies);
    return getProcessECNNotification_Pt();
  }
  
  public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processECNNotification_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessECNNotification_Pt();
  }
  
  public be.e1.bssv.J563004.ecoproxy.ProcessECNNotification getProcessECNNotification_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processECNNotification_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessECNNotification_Pt();
  }
    
}