package be.e1.bssv.J563004.ecoproxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Fri Jan 17 16:26:00 EST 2014  
 */

public interface ProcessECNNotification extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/P2SINT0001/ECNNotification/processECNNotification}process   */

  public be.e1.bssv.J563004.com.beav.e1.ecnnotification.ECNNotificationResponse process(be.e1.bssv.J563004.com.beav.e1.ecnnotification.ECNNotification payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.J563004.com.beav.e1.ecnnotification.ECNNotification payload) throws java.rmi.RemoteException ;
  
}