package be.e1.bssv.util.J569806.FtpListing;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Mon Dec 02 11:24:14 EST 2013  
 */

public interface Processfilelisting_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ProcessFileListing_Pt  
     // Port Type: ProcessFileListing   
     //***********************************
     
  /**
   * returns ProcessFileListing_Pt port in this service 
   */
  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getProcessFileListing_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }