package be.e1.bssv.util.J569806.FtpListing;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Mon Dec 02 11:24:14 EST 2013  
 */

public interface ProcessFileListing extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/FTPManager/FTPListing/processFileListing}process   */

  public be.e1.bssv.util.J569806.com.beav.fmw.filelisting.FileListingReply process(be.e1.bssv.util.J569806.com.beav.fmw.filelisting.FileListingRequest payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.util.J569806.com.beav.fmw.filelisting.FileListingRequest payload) throws java.rmi.RemoteException ;
  
}