package be.e1.bssv.util.J569806.FtpListing;

/**
 * Generated class, do not edit.
 *
 * This stub class was generated by weblogic
 * webservice stub gen on Mon Dec 02 11:24:14 EST 2013 
 */

public class ProcessFileListing_Stub 
     extends weblogic.wsee.jaxrpc.StubImpl
     implements be.e1.bssv.util.J569806.FtpListing.ProcessFileListing, /**/java.io.Serializable
{

  public ProcessFileListing_Stub(weblogic.wsee.wsdl.WsdlPort port, 
                        weblogic.wsee.jaxrpc.ServiceImpl service) 
    throws javax.xml.rpc.ServiceException
  {
    super(port, be.e1.bssv.util.J569806.FtpListing.ProcessFileListing.class, service);
  }
  
    
  /**
   * Operation Name : {http://xmlns.oracle.com/FTPManager/FTPListing/processFileListing}process   */

  public be.e1.bssv.util.J569806.com.beav.fmw.filelisting.FileListingReply process(be.e1.bssv.util.J569806.com.beav.fmw.filelisting.FileListingRequest payload) throws java.rmi.RemoteException {

    java.util.ArrayList _args = new java.util.ArrayList();
    _args.add(payload);
    
    try {
            java.lang.Object _result = _invoke("process", _args.toArray());
      return (be.e1.bssv.util.J569806.com.beav.fmw.filelisting.FileListingReply)_result;
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {

      
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
  }  public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.util.J569806.com.beav.fmw.filelisting.FileListingRequest payload) throws java.rmi.RemoteException  {
    java.util.ArrayList _args = new java.util.ArrayList();

    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY, "true");
    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY, apc);
    _setProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY, "process");
    _setProperty(weblogic.wsee.async.AsyncConstants.OPERATION_NAME_PROPERTY,
                 "process");
    _setProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY, "be.e1.bssv.util.J569806.com.beav.fmw.filelisting.FileListingReply");
    _args.add(payload);
    
    try {
      java.lang.Object _result = _invoke("process", _args.toArray());
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
    finally {
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY);

    }
  }
   
    
  private Object writeReplace() throws java.io.ObjectStreamException {
    java.util.HashMap map = new java.util.HashMap();
            map.put("processFileListing_pt", "ProcessFileListing_Pt");
            
    return new weblogic.wsee.tools.clientgen.stubgen.StubSerialWrapper(
      "be.e1.bssv.util.J569806.FtpListing.Processfilelisting_Client_Ep",
      (String)map.get(_getPortName()),
      _getUserProperties());
  }
}