package be.e1.bssv.util.J569806.FtpListing;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Mon Dec 02 11:24:14 EST 2013 */

public class Processfilelisting_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.util.J569806.FtpListing.Processfilelisting_Client_Ep {

  public Processfilelisting_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/util/J569806/FtpListing/Processfilelisting_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public Processfilelisting_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public Processfilelisting_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://xmlns.oracle.com/FTPManager/FTPListing/processFileListing", "processfilelisting_client_ep"),
          "be/e1/bssv/util/J569806/FtpListing/Processfilelisting_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: ProcessFileListing_Pt 
  // Port Type: ProcessFileListing 
  //***********************************

  be.e1.bssv.util.J569806.FtpListing.ProcessFileListing mvar_ProcessFileListing_Pt;

  /**
   * returns ProcessFileListing_Pt port in this service 
   */
  public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_ProcessFileListing_Pt == null) {
      mvar_ProcessFileListing_Pt =
        new be.e1.bssv.util.J569806.FtpListing.ProcessFileListing_Stub(_getPort("processFileListing_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_ProcessFileListing_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_ProcessFileListing_Pt;
  }

  /**
   * @Deprecated  Use getProcessFileListing_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getProcessFileListing_Pt();
  }

  public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getProcessFileListing_Pt();
  }
  
      public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFileListing_pt", policyInputStream, true, true);
    return getProcessFileListing_Pt();
  }

  public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFileListing_pt", policyInputStream, inbound, outbound);
    return getProcessFileListing_Pt();
  }
 
  public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFileListing_pt", null, inboundPolicies, outboundPolicies);
    return getProcessFileListing_Pt();
  }
  
  public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFileListing_pt", null, inboundPolicies, outboundPolicies);
    return getProcessFileListing_Pt();
  }
  
  public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFileListing_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessFileListing_Pt();
  }
  
  public be.e1.bssv.util.J569806.FtpListing.ProcessFileListing getProcessFileListing_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFileListing_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessFileListing_Pt();
  }
    
}