package be.e1.bssv.J564203.ComplianceProxy;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Sat Sep 07 17:25:44 EDT 2013 */

public class Processcompliancescreening_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.J564203.ComplianceProxy.Processcompliancescreening_Client_Ep {

  public Processcompliancescreening_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/J564203/ComplianceProxy/Processcompliancescreening_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public Processcompliancescreening_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public Processcompliancescreening_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://xmlns.oracle.com/KewillComplianceManager/ComplianceScreening/processComplianceScreening", "processcompliancescreening_client_ep"),
          "be/e1/bssv/J564203/ComplianceProxy/Processcompliancescreening_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: ProcessComplianceScreening_Pt 
  // Port Type: ProcessComplianceScreening 
  //***********************************

  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening mvar_ProcessComplianceScreening_Pt;

  /**
   * returns ProcessComplianceScreening_Pt port in this service 
   */
  public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_ProcessComplianceScreening_Pt == null) {
      mvar_ProcessComplianceScreening_Pt =
        new be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening_Stub(_getPort("processComplianceScreening_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_ProcessComplianceScreening_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_ProcessComplianceScreening_Pt;
  }

  /**
   * @Deprecated  Use getProcessComplianceScreening_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getProcessComplianceScreening_Pt();
  }

  public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getProcessComplianceScreening_Pt();
  }
  
      public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processComplianceScreening_pt", policyInputStream, true, true);
    return getProcessComplianceScreening_Pt();
  }

  public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processComplianceScreening_pt", policyInputStream, inbound, outbound);
    return getProcessComplianceScreening_Pt();
  }
 
  public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processComplianceScreening_pt", null, inboundPolicies, outboundPolicies);
    return getProcessComplianceScreening_Pt();
  }
  
  public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processComplianceScreening_pt", null, inboundPolicies, outboundPolicies);
    return getProcessComplianceScreening_Pt();
  }
  
  public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processComplianceScreening_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessComplianceScreening_Pt();
  }
  
  public be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processComplianceScreening_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessComplianceScreening_Pt();
  }
    
}