package be.e1.bssv.J564203.ComplianceProxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Sat Sep 07 17:25:44 EDT 2013  
 */

public interface Processcompliancescreening_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ProcessComplianceScreening_Pt  
     // Port Type: ProcessComplianceScreening   
     //***********************************
     
  /**
   * returns ProcessComplianceScreening_Pt port in this service 
   */
  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getProcessComplianceScreening_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564203.ComplianceProxy.ProcessComplianceScreening getProcessComplianceScreening_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }