package be.e1.bssv.util.J560011.ADLookupProxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Wed Nov 20 15:22:47 EST 2013  
 */

public interface GetGroupUserData extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/ADGroupUserData/ADGroupUserData/getGroupUserData}process   */

  public be.e1.bssv.util.J560011.com.beav.e1.adgroupuserdata.ADGroupUserDataReply process(be.e1.bssv.util.J560011.com.beav.e1.adgroupuserdata.ADGroupUserDataRequest payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.util.J560011.com.beav.e1.adgroupuserdata.ADGroupUserDataRequest payload) throws java.rmi.RemoteException ;
  
}