package be.e1.bssv.util.J560011.ADLookupProxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Wed Nov 20 15:22:47 EST 2013  
 */

public interface Getgroupuserdata_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: GetGroupUserData_Pt  
     // Port Type: GetGroupUserData   
     //***********************************
     
  /**
   * returns GetGroupUserData_Pt port in this service 
   */
  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getGetGroupUserData_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }