package be.e1.bssv.util.J560011.ADLookupProxy;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Wed Nov 20 15:22:47 EST 2013 */

public class Getgroupuserdata_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.util.J560011.ADLookupProxy.Getgroupuserdata_Client_Ep {

  public Getgroupuserdata_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/util/J560011/ADLookupProxy/Getgroupuserdata_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public Getgroupuserdata_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public Getgroupuserdata_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://xmlns.oracle.com/ADGroupUserData/ADGroupUserData/getGroupUserData", "getgroupuserdata_client_ep"),
          "be/e1/bssv/util/J560011/ADLookupProxy/Getgroupuserdata_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: GetGroupUserData_Pt 
  // Port Type: GetGroupUserData 
  //***********************************

  be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData mvar_GetGroupUserData_Pt;

  /**
   * returns GetGroupUserData_Pt port in this service 
   */
  public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_GetGroupUserData_Pt == null) {
      mvar_GetGroupUserData_Pt =
        new be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData_Stub(_getPort("getGroupUserData_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_GetGroupUserData_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_GetGroupUserData_Pt;
  }

  /**
   * @Deprecated  Use getGetGroupUserData_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getGetGroupUserData_Pt();
  }

  public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getGetGroupUserData_Pt();
  }
  
      public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("getGroupUserData_pt", policyInputStream, true, true);
    return getGetGroupUserData_Pt();
  }

  public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("getGroupUserData_pt", policyInputStream, inbound, outbound);
    return getGetGroupUserData_Pt();
  }
 
  public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("getGroupUserData_pt", null, inboundPolicies, outboundPolicies);
    return getGetGroupUserData_Pt();
  }
  
  public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("getGroupUserData_pt", null, inboundPolicies, outboundPolicies);
    return getGetGroupUserData_Pt();
  }
  
  public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("getGroupUserData_pt", operationName, inboundPolicies, outboundPolicies);
    return getGetGroupUserData_Pt();
  }
  
  public be.e1.bssv.util.J560011.ADLookupProxy.GetGroupUserData getGetGroupUserData_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("getGroupUserData_pt", operationName, inboundPolicies, outboundPolicies);
    return getGetGroupUserData_Pt();
  }
    
}