package be.e1.bssv.util.J569801.requestproxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Tue Feb 11 09:27:35 EST 2014  
 */

public interface ProcessFTP extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://beaerospace.com/FTPService/FTPService/ProcessFTP}process   */

  public be.e1.bssv.util.J569801.com.beaerospace.ftpservice.ftpservice.processftp.ProcessResponse process(be.e1.bssv.util.J569801.com.beaerospace.ftpservice.ftpservice.processftp.Process payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.util.J569801.com.beaerospace.ftpservice.ftpservice.processftp.Process payload) throws java.rmi.RemoteException ;
  
}