package be.e1.bssv.util.J569801.requestproxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Tue Feb 11 09:27:35 EST 2014  
 */

public interface Processftp_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ProcessFTP_Pt  
     // Port Type: ProcessFTP   
     //***********************************
     
  /**
   * returns ProcessFTP_Pt port in this service 
   */
  be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getProcessFTP_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }