package be.e1.bssv.util.J569801.requestproxy;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Tue Feb 11 09:27:35 EST 2014 */

public class Processftp_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.util.J569801.requestproxy.Processftp_Client_Ep {

  public Processftp_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/util/J569801/requestproxy/Processftp_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public Processftp_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public Processftp_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://beaerospace.com/FTPService/FTPService/ProcessFTP", "processftp_client_ep"),
          "be/e1/bssv/util/J569801/requestproxy/Processftp_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: ProcessFTP_Pt 
  // Port Type: ProcessFTP 
  //***********************************

  be.e1.bssv.util.J569801.requestproxy.ProcessFTP mvar_ProcessFTP_Pt;

  /**
   * returns ProcessFTP_Pt port in this service 
   */
  public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_ProcessFTP_Pt == null) {
      mvar_ProcessFTP_Pt =
        new be.e1.bssv.util.J569801.requestproxy.ProcessFTP_Stub(_getPort("ProcessFTP_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_ProcessFTP_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_ProcessFTP_Pt;
  }

  /**
   * @Deprecated  Use getProcessFTP_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getProcessFTP_Pt();
  }

  public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getProcessFTP_Pt();
  }
  
      public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("ProcessFTP_pt", policyInputStream, true, true);
    return getProcessFTP_Pt();
  }

  public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("ProcessFTP_pt", policyInputStream, inbound, outbound);
    return getProcessFTP_Pt();
  }
 
  public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("ProcessFTP_pt", null, inboundPolicies, outboundPolicies);
    return getProcessFTP_Pt();
  }
  
  public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("ProcessFTP_pt", null, inboundPolicies, outboundPolicies);
    return getProcessFTP_Pt();
  }
  
  public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("ProcessFTP_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessFTP_Pt();
  }
  
  public be.e1.bssv.util.J569801.requestproxy.ProcessFTP getProcessFTP_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("ProcessFTP_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessFTP_Pt();
  }
    
}