package be.e1.bssv.J564200.ProcessProxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Wed Mar 12 00:39:08 EDT 2014  
 */

public interface FedExShipmentRequest extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/FedExShipServices/FedExShipments/fedExShipmentRequest}process   */

  public be.e1.bssv.J564200.com.beone.fedex.beshipments.ProcessShipmentReply process(be.e1.bssv.J564200.com.beone.fedex.beshipments.ProcessShipmentRequest payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.J564200.com.beone.fedex.beshipments.ProcessShipmentRequest payload) throws java.rmi.RemoteException ;
  
}