package be.e1.bssv.J564200.ProcessProxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Wed Mar 12 00:39:08 EDT 2014  
 */

public interface Fedexshipmentrequest_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: FedExShipmentRequest_Pt  
     // Port Type: FedExShipmentRequest   
     //***********************************
     
  /**
   * returns FedExShipmentRequest_Pt port in this service 
   */
  be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getFedExShipmentRequest_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.ProcessProxy.FedExShipmentRequest getFedExShipmentRequest_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }