package be.e1.bssv.J564200.DocumentUploadProxy;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Tue Mar 04 19:33:52 EST 2014 */

public class Processfedexuploadimage_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.J564200.DocumentUploadProxy.Processfedexuploadimage_Client_Ep {

  public Processfedexuploadimage_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/J564200/DocumentUploadProxy/Processfedexuploadimage_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public Processfedexuploadimage_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public Processfedexuploadimage_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://xmlns.oracle.com/FedExShipServices/FedExUploadDocs/processFedExUploadImage", "processfedexuploadimage_client_ep"),
          "be/e1/bssv/J564200/DocumentUploadProxy/Processfedexuploadimage_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: ProcessFedExUploadImage_Pt 
  // Port Type: ProcessFedExUploadImage 
  //***********************************

  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage mvar_ProcessFedExUploadImage_Pt;

  /**
   * returns ProcessFedExUploadImage_Pt port in this service 
   */
  public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_ProcessFedExUploadImage_Pt == null) {
      mvar_ProcessFedExUploadImage_Pt =
        new be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage_Stub(_getPort("processFedExUploadImage_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_ProcessFedExUploadImage_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_ProcessFedExUploadImage_Pt;
  }

  /**
   * @Deprecated  Use getProcessFedExUploadImage_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getProcessFedExUploadImage_Pt();
  }

  public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getProcessFedExUploadImage_Pt();
  }
  
      public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFedExUploadImage_pt", policyInputStream, true, true);
    return getProcessFedExUploadImage_Pt();
  }

  public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFedExUploadImage_pt", policyInputStream, inbound, outbound);
    return getProcessFedExUploadImage_Pt();
  }
 
  public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFedExUploadImage_pt", null, inboundPolicies, outboundPolicies);
    return getProcessFedExUploadImage_Pt();
  }
  
  public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFedExUploadImage_pt", null, inboundPolicies, outboundPolicies);
    return getProcessFedExUploadImage_Pt();
  }
  
  public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFedExUploadImage_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessFedExUploadImage_Pt();
  }
  
  public be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("processFedExUploadImage_pt", operationName, inboundPolicies, outboundPolicies);
    return getProcessFedExUploadImage_Pt();
  }
    
}