package be.e1.bssv.J564200.DocumentUploadProxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Tue Mar 04 19:33:52 EST 2014  
 */

public interface ProcessFedExUploadImage extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/FedExShipServices/FedExUploadDocs/processFedExUploadImage}process   */

  public be.e1.bssv.J564200.com.beone.fedex.beuploadimage.UploadImagesReply process(be.e1.bssv.J564200.com.beone.fedex.beuploadimage.UploadImagesRequest payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.J564200.com.beone.fedex.beuploadimage.UploadImagesRequest payload) throws java.rmi.RemoteException ;
  
}