package be.e1.bssv.J564200.DocumentUploadProxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Tue Mar 04 19:33:52 EST 2014  
 */

public interface Processfedexuploadimage_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ProcessFedExUploadImage_Pt  
     // Port Type: ProcessFedExUploadImage   
     //***********************************
     
  /**
   * returns ProcessFedExUploadImage_Pt port in this service 
   */
  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getProcessFedExUploadImage_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J564200.DocumentUploadProxy.ProcessFedExUploadImage getProcessFedExUploadImage_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }