
package be.e1.bssv.J564200.CloseShipmentProxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
/*
import javax.xml.ws.WebServiceFeature;
*/

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "closefedexshipment_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/FedExShipServices/FedExShipments/closeFedExShipment",
                  wsdlLocation =
                  "http://fmwdev.beav.com:80/soa-infra/services/Utilities/FedExShipments/closefedexshipment_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FFedExShipServices%2FFedExShipments%2FcloseFedExShipment%7Dclosefedexshipment_client_ep")
public class ClosefedexshipmentClientEp
    extends Service
{

    private final static URL CLOSEFEDEXSHIPMENTCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CLOSEFEDEXSHIPMENTCLIENTEP_EXCEPTION;
    private final static QName CLOSEFEDEXSHIPMENTCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/FedExShipServices/FedExShipments/closeFedExShipment",
                  "closefedexshipment_client_ep");

    static
    {
        URL url = null;
        WebServiceException e = null;
        try
        {
            url =
                new URL("http://fmwdev.beav.com:80/soa-infra/services/Utilities/FedExShipments/closefedexshipment_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FFedExShipServices%2FFedExShipments%2FcloseFedExShipment%7Dclosefedexshipment_client_ep");
        }
        catch (MalformedURLException ex)
        {
            e = new WebServiceException(ex);
        }
        CLOSEFEDEXSHIPMENTCLIENTEP_WSDL_LOCATION = url;
        CLOSEFEDEXSHIPMENTCLIENTEP_EXCEPTION = e;
    }

    public ClosefedexshipmentClientEp()
    {
        super(__getWsdlLocation(), CLOSEFEDEXSHIPMENTCLIENTEP_QNAME);
    }

/*
    public ClosefedexshipmentClientEp(WebServiceFeature... features)
    {
        super(__getWsdlLocation(), CLOSEFEDEXSHIPMENTCLIENTEP_QNAME, features);
    }

    public ClosefedexshipmentClientEp(URL wsdlLocation, WebServiceFeature... features)
    {
        super(wsdlLocation, CLOSEFEDEXSHIPMENTCLIENTEP_QNAME, features);
    }

    public ClosefedexshipmentClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features)
    {
        super(wsdlLocation, serviceName, features);
    }
*/

    public ClosefedexshipmentClientEp(URL wsdlLocation)
    {
        super(wsdlLocation, CLOSEFEDEXSHIPMENTCLIENTEP_QNAME);
    }
    public ClosefedexshipmentClientEp(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }
    /**
     *
     * @return
     *     returns CloseFedExShipment
     */
    @WebEndpoint(name = "closeFedExShipment_pt")
    public CloseFedExShipment getCloseFedExShipmentPt()
    {
        return super.getPort(new QName("http://xmlns.oracle.com/FedExShipServices/FedExShipments/closeFedExShipment",
                                       "closeFedExShipment_pt"), CloseFedExShipment.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CloseFedExShipment
     */
    /*
    @WebEndpoint(name = "closeFedExShipment_pt")
    public CloseFedExShipment getCloseFedExShipmentPt(WebServiceFeature... features)
    {
        return super.getPort(new QName("http://xmlns.oracle.com/FedExShipServices/FedExShipments/closeFedExShipment",
                                       "closeFedExShipment_pt"), CloseFedExShipment.class, features);
    }
    */

    private static URL __getWsdlLocation()
    {
        if (CLOSEFEDEXSHIPMENTCLIENTEP_EXCEPTION != null)
        {
            throw CLOSEFEDEXSHIPMENTCLIENTEP_EXCEPTION;
        }
        return CLOSEFEDEXSHIPMENTCLIENTEP_WSDL_LOCATION;
    }

}
