package be.e1.bssv.J564200.CloseShipmentProxy;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.2.0.0.6668
public class closeFedExShipment_ptClient
{
    public static void main(String[] args)
    {
        ClosefedexshipmentClientEp closefedexshipmentClientEp = new ClosefedexshipmentClientEp();
        CloseFedExShipment closeFedExShipment = closefedexshipmentClientEp.getCloseFedExShipmentPt();
        // Add your code to call the desired methods.


    }
}
